version: '3.9'
name: NG.CASH-WALLET
services:
  frontend:
    container_name: NG.CASH-frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app/frontend
    volumes:
      - ./frontend/src:/app/frontend/src
    depends_on:
      - backend
  backend:
    container_name: NG.CASH-backend
    build: ./backend
    ports:
      - 8000:8000
    platform: linux/x86_64
    working_dir: /app/backend
    command: run dev
    volumes:
      - ./backend/src:/app/backend/src
    depends_on:
      - db
    env_file:
      - ../.env/
    networks:
      - postgres
  db:
    image: postgres:14.1-alpine
    container_name: NG.CASH-db
    platform: linux/x86_64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: 'always'
    networks:
      - postgres
    cap_add:
      - SYS_NICE

  pgadmin:
    container_name: NG.CASH-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin1234"
    volumes:
     - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

volumes:
 db-data:
 pgadmin-data:
networks:
  postgres:
    driver: bridge
